ShoppingWebApp/Controllers/CartController.cs
using Data_Layer.Repository.Implementation;
using Data_Layer.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShoppingWebApp.Models;

namespace ShoppingWebApp.Controllers
{
    public class CartController : Controller
    {
        IProductRepository productRepository = null;
        public CartController()
        {
            productRepository = new ProductRepository();
        }

        [Authorize(Policy = "UserPolicy")]
        public IActionResult Index()
        {

            var cart = HttpContext.Session.GetComplexData<List<CartItem>>("CART");
            List<CartItem> list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        [Authorize(Roles = "User")]
        public IActionResult Checkout()
        {
            var cart = HttpContext.Session.GetComplexData<List<CartItem>>("CART");
            List<CartItem> list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        //POST - ADD
        [Authorize(Policy = "UserPolicy")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(int ProductId, int Quantity)
        {
            var product = productRepository.GetProductById(ProductId);
            var cart = HttpContext.Session.GetComplexData<List<CartItem>>("CART");
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(i => i.ProductId == product.ProductId))
                {
                    foreach (var item in list)
                    {
                        if (item.ProductId == product.ProductId)
                        {
                            item.Quantity += Quantity;
                        }
                    }
                    HttpContext.Session.SetComplexData("CART", list);
                }

                else 
                {

                    var item = new CartItem();
                    item.ProductId = product.ProductId;
                    item.ProductName = product.ProductName;
                    item.Price = product.Price;
                    item.Image = product.Image;
                    item.Quantity = Quantity;
                    list.Add(item);
                    HttpContext.Session.SetComplexData("CART", list);
                }
            }
            else 
            {
                var item = new CartItem();
                item.ProductId = product.ProductId;
                item.ProductName = product.ProductName;
                item.Price = product.Price;
                item.Image = product.Image;
                item.Quantity = Quantity;
                var list = new List<CartItem>();
                list.Add(item);
                HttpContext.Session.SetComplexData("CART", list);
            }
            return NoContent();
        }

        //GET - REMOVE
        [Authorize(Policy = "UserPolicy")]
        public IActionResult Remove(int? ProductId)
        {
            if (ProductId == null)
            {
                return NotFound();
            }
            var product = productRepository.GetProductById((int)ProductId);
            if (product == null)
            {
                return NotFound();
            }
            var cart = HttpContext.Session.GetComplexData<List<CartItem>>("CART");
            List<CartItem> list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
                if (list.Exists(x => x.ProductId == ProductId))
                {
                    foreach (var item in list)
                    {
                        if (item.ProductId == ProductId)
                        {
                            list.Remove(item);
                            break;
                        }
                    }
                }
                HttpContext.Session.SetComplexData("CART", list);
            }
            return RedirectToAction("Index");
        }
    }
}

#region ExtendSession
public static class SessionExtensions
{
    public static T GetComplexData<T>(this ISession session, string key)
    {
        var data = session.GetString(key);
        if (data == null)
        {
            return default(T);
        }
        return JsonConvert.DeserializeObject<T>(data);
    }

    public static void SetComplexData(this ISession session, string key, object value)
    {
        session.SetString(key, JsonConvert.SerializeObject(value));
    }
}

#endregion

ShoppingWebApp/Controllers/GuestController.cs
using BusinessObject;
using Data_Layer.Repository.Implementation;
using Data_Layer.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Ocsp;
using ShoppingWebApp.Models;

namespace ShoppingWebApp.Controllers
{
    public class GuestController : Controller
    {
        IProductRepository productRepository = null;
        ICategoryRepository categoryRepository = null;
        public GuestController()
        {
            productRepository = new ProductRepository();
            categoryRepository = new CategoryRepository();
        }
        [Authorize(Policy = "UserPolicy")]
        public IActionResult Index(int? categoryId, string? name)
        {   
            IEnumerable<Product> products = productRepository.GetProductList();
            if (categoryId != null)
            {
                products = products.Where(product => product.CategoryId.Equals(categoryId)).ToList();
            }
            if (!string.IsNullOrEmpty(name))  {
                products = products.Where(product => product.ProductName.ToLower().Contains(name.ToLower()));
            }
            IEnumerable<Category> listCategory = categoryRepository.GetCategoryList();
            GuestViewModel models = new GuestViewModel();
            models.Products = products.ToList();
            models.Categories = listCategory;
            if (TempData["CheckoutMessage"] != null)
            {
                ViewBag.Message = TempData["CheckoutMessage"];
                TempData.Remove("CheckoutMessage");
            }
            return View(models);
        }
    }
}

ShoppingWebApp/Controllers/LogOutController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace ShoppingWebApp.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Login");
        }
    }
}

ShoppingWebApp/Controllers/UsersController.cs
using BusinessObject;
using Data_Layer.Repository.Implementation;
using Data_Layer.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ShoppingWebApp.Controllers
{
    public class UsersController : Controller
    {
        IUserRepository userRepository = null;
        IRoleRepository roleRepository = null;

        public UsersController()
        {
            userRepository = new UserRepository();
            roleRepository = new RoleRepository();
        }


        // GET: UsersController
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var userList = userRepository.GetUserList();
            return View(userList);
        }

        public ActionResult Filter(string status)
        {
            IEnumerable<User> accountList;
            if (status == null)
            {
                return RedirectToAction(nameof(Index));

            }
            else if (status.Equals("true"))
            {
                accountList = userRepository.GetActiveUser();
            }
            else
            {
                accountList = userRepository.GetInactiveUser();
            }
            return View(accountList);

        }


        // GET: UsersController/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            var user = userRepository.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }


        // GET: UsersController/Edit/5
        //[Authorize(Roles = "Admin")]
        //public ActionResult Edit(int id)
        //{
        //    User user = userRepository.GetUserById(id);
        //    ViewData["Role"] = new SelectList(roleRepository.GetRolesList(), "RoleId", "RoleName", user.Role);
        //    return View(user);
        //}

        // POST: UsersController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, User user)
        //{
        //    try
        //    {
        //        if (id != user.UserId)
        //        {
        //            return NotFound();
        //        }

        //        if (ModelState.IsValid)
        //        {
        //            userRepository.UpdateUser(user);
        //        }

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Message = ex.Message;
        //        return RedirectToAction(nameof(Index));
        //    }
        //}

        //[HttpPost]
        //public ActionResult SetStatus([FromForm] int id, [FromForm] bool status)
        //{
        //    try
        //    {
        //        userRepository.SetAccountStatus(id, status);

        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.Message = ex.Message;

        //    }
        //    return RedirectToAction(nameof(Index));
        //}


    }
}

ShoppingWebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Data_Layer.Repository.Implementation
@using Data_Layer.Repository.Interface
@using BusinessObject
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CLothes store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    <style>
        .dataTables_filter {
            float: right !important;
        }
    </style>
</head>

<body>
    @{
        IUserRepository userRepository = new UserRepository();
    }
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container">

                <a class="navbar-brand bold" asp-area="" asp-controller="Home" asp-action="Index">Clothes store</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-between"> 
                    <ul class="navbar-nav ml-auto">
                        @if (User.Claims.FirstOrDefault(cl => cl.Type == ClaimTypes.Email) != null)
                        { 
                            string email = User.Claims.FirstOrDefault(cl => cl.Type == ClaimTypes.Email).Value;
                            User loginUser = userRepository.GetUser(email);

                            @if (User.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.Role)).Value.Equals("User"))
                            { // Normal User
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Guest" asp-action="Index">Shopping</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="OrderHistory" asp-action="Index">Order History</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Log out</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-controller="@loginUser.RoleNavigation.RoleName" asp-action="Index">
                                        <i class="fas fa-user"></i> Welcome, @loginUser.FullName
                                    </a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" style="padding-top:0;" asp-area="" asp-controller="Cart" asp-action="Index">
                                        <span style="font-size: 1.5em; color: Tomato;">
                                            <i class="fas fa-shopping-cart"></i>
                                        </span>
                                    </a>
                                </li>
                            }
                            else if (User.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.Role)).Value.Equals("Admin"))
                            { // Admin
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Category</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Product</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Account</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Order</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Statistic" asp-action="Index">Statistic</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Log out</a>
                                </li>
                                <li class="nav-item ml-3">
                                    <a class="nav-link text-dark" asp-controller="User" asp-action="Index">
                                        <i class="fas fa-user"></i> Welcome, @loginUser.FullName
                                    </a>
                                </li>
                            }
                        }
                        else
                        { // Not Login User
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Guest" asp-action="Index">Shopping</a>
                            </li>
                            <li class="nav-item ml-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Log in</a>
                            </li>
                            <li class="nav-item ml-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Signup" asp-action="Index">Sign up</a>
                            </li>
                            <li class="nav-item ml-3">
                                <a class="nav-link text-dark" style="padding-top:0;" asp-area="" asp-controller="Cart" asp-action="Index">
                                    <span style="font-size: 1.5em; color: Tomato;">
                                        <i class="fas fa-shopping-cart"></i>
                                    </span>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 my-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Clothes store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>