ShoppingWebApp/Controllers/SignUpController.cs
using BusinessObject;
using Data_Layer.Repository.Implementation;
using Data_Layer.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShoppingWebApp.Models;

namespace ShoppingWebApp.Controllers
{
    public class SignupController : Controller
    {
        IUserRepository userRepository = new UserRepository();

        //private string defaultAvatar = "https://firebasestorage.googleapis.com/v0/b/clothshopping-6fd63.appspot.com/o/UserAvatar_Default.png?alt=media&token=3b553ee8-9965-474d-a6ef-5149e4c86273";


        [AllowAnonymous]
        public IActionResult Index(string? email, string? fullname)
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            SignUpModel userEditModel = new SignUpModel();

            return View(userEditModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(SignUpModel user)
        {
            bool isError = false;
            string message = string.Empty;
            if (ModelState.IsValid)
            {
                string password = user.Password;
                string confirm = user.Confirm;
                if (!password.Equals(confirm))
                {
                    isError = true;
                    message = "Confirm and Password are not matched!!";
                }
                else
                {
                    string email = user.Email;
                    string fullname = user.FullName;
                    bool status = true; 
                    int role = 2; 

                    try
                    {
                        User newUser = new User()
                        {
                            FullName = fullname,
                            Email = email,
                            Password = BCrypt.Net.BCrypt.HashPassword(password),
                            Role = role,
                            Status = status,
                            //Avatar = defaultAvatar
                        };

                        userRepository.SignUp(newUser);

                    }
                    catch (Exception ex)
                    {
                        isError = true;
                        message = ex.Message;
                    }
                }
                
            }
           
            if (isError)
            {
                ViewBag.Error = message;
                return View(user);
            }
            TempData["SignUp"] = "Sign up successfully! You can login now!";
            return RedirectToAction("Index", "Login");
        }

        [AllowAnonymous]
        public IActionResult Google()
        {
            return RedirectToAction("Google", "Login");
        }
    }
}

ShoppingWebApp/Views/Signup/Index.cshtml
@model SignUpModel

@{
    ViewData["Title"] = "Sign Up";
}

<h1>Sign Up</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.AntiForgeryToken()
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="FullName"></label>
                <input asp-for="FullName" class="form-control" required />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" type="password" class="form-control" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Confirm"></label>
                <input asp-for="Confirm" type="password" class="form-control" required />
                <span asp-validation-for="Confirm" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Sign Up" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div class="col-md-6">
        <a asp-action="Google" asp-controller="Signup" class="btn btn-outline-primary" name="Google"><i class="fab fa-google"></i> Sign Up with Google</a>
    </div>

    @if (!string.IsNullOrEmpty(ViewBag.Error))
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.Error
        </div>
    }

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}